version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run $TEST
  docker-build-and-run:
    machine: true
    steps:
      - run: ls
      - run: docker build -t shivkaps/cypress-mastery .
      - run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      - run: docker push shivkaps/cypress-mastery
workflows:
    build-and-test:
      jobs:
        - build-and-test
    docker-build-and-run:
      jobs:
        - docker-build-and-run
        
